//
//  LoginSceneInteractor.swift
//  CS
//
//  Created by Коломенский Александр on 22.02.2023.
//  Copyright (c) 2023 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so

import UIKit

protocol LoginSceneBusinessLogic
{
  func doSomething(request: LoginScene.Something.Request)
}

protocol LoginSceneDataStore
{
  //var name: String { get set }
}

class LoginSceneInteractor: LoginSceneBusinessLogic, LoginSceneDataStore
{
  var presenter: LoginScenePresentationLogic?
  var worker: LoginSceneWorker?
  //var name: String = ""
  
  // MARK: Do something
  
  func doSomething(request: LoginScene.Something.Request)
  {
    worker = LoginSceneWorker()
    worker?.doSomeWork()
    
    let response = LoginScene.Something.Response()
    presenter?.presentSomething(response: response)
  }
}
